var start_node = null;
var end_node = null;
var walls = [];
var start_color = "yellow";
var end_color = "orange";
var wall_color = "black";
var unmarked_color = "rgba(255, 255, 255, 0.8)";
var matrix_size = 20;
var global_grid;
var inf = Math.pow(10, 1000);